### ISSUE TITLE
Doesn't split correclty price under 100.

### ISSUE THREAD

**Issue by a7993n** [omer-os/next-bill-calculator#1]
LOL, If you enter 100 it doesn't split correctly :)

**Comment by omer-os** [comment]
> LOL, If you enter 100 it doesn't split correctly :)

Hi! Thanks for checking out the repo. Just to clarify, in Iraq, we don't have a 100-dinar note or coin in circulation. The smallest denomination currently available is 250 dinars, which is why i set up to reflect that. The code is designed to handle amounts accordingly. Hope that clears things up! 🙂
